# Generated by Django 2.0.3 on 2018-05-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180531_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
