# Generated by Django 2.0.3 on 2018-05-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newarival'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarival',
            name='previous_product_price',
            field=models.FloatField(default=0),
        ),
    ]
