# Generated by Django 2.0.3 on 2018-06-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
    ]
