# Generated by Django 2.0.3 on 2018-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180609_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.TextField(null=True),
        ),
    ]
